# _config.yml
title: Marco Podda - Researcher # Replace with your actual name
author:
  name: Marco Podda
  email: marco.podda@unipi.it
description: >- # This will populate your site's <meta name="description"> tag.
  A brief description of your research and expertise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Sass configuration (Crucial for your _sass structure)
sass:
  sass_dir: assets/css/_sass # This points to your _sass directory
  style: compressed # Compresses CSS for production

# Exclude from processing.
# The following items will not be processed, by default.
# For a full list of exclusions, see: https://jekyllrb.com/docs/configuration/#exclusion-from-processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
