name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2" # Use a recent Ruby 3.x version, matching your local
          bundler-cache: true # Install dependencies with Bundler
      - name: Build Jekyll site
        run: bundle exec jekyll build --incremental
        env:
          JEKYLL_ENV: production # Set Jekyll environment for production build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site # Path to your Jekyll build output

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
